#!/usr/bin/env python3
"""
GeoChat Grounding Output Parser.

Parses GeoChat's raw textual response containing region tags (<p>label</p>)
and normalized coordinate tokens ({<ymin><xmin><ymax><xmax>|<score>}) into
structured visual evidence dictionaries compatible with the SatQuery API contract.
"""

import math
import re
from typing import Dict, List, Any, Optional


def clean_geochat_text(response_text: str) -> str:
    """Remove model-only grounding markup while preserving the narrative answer."""
    if not response_text:
        return ""
    # Remove coordinate token structures: {<69><51><73><75>|<1>}
    text = re.sub(r"\{<\d+><\d+><\d+><\d+>\|[^}]+\}", "", response_text)
    # Some checkpoints / prompt variants emit an explicit box tag instead.
    text = re.sub(r"<box>\s*\[\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*,\s*-?\d+(?:\.\d+)?\s*\]\s*</box>", "", text, flags=re.I)
    # Remove delim tokens
    text = re.sub(r"<delim>", "", text)
    # Remove XML region tags: <p>label</p> -> label
    text = re.sub(r"<p>(.*?)</p>", r"\1", text)
    # Clean multiple spaces and trailing whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text


def normalize_visual_box(
    box: List[float], *, coordinate_space: str = "percent", image_width: Optional[int] = None,
    image_height: Optional[int] = None,
) -> List[float]:
    """Return a sorted, clipped ``[xmin, ymin, xmax, ymax]`` percentage box.

    ``coordinate_space`` is deliberately explicit: ``percent`` is GeoChat's
    documented 0--100 grid, ``grid_1000`` is a 0--1000 VLM grid, and ``pixels``
    requires the source image dimensions.  Never infer pixel versus percentage
    from magnitude: a 90px coordinate is ambiguous and caused prior bad boxes.
    """
    if len(box) != 4:
        raise ValueError("A visual grounding box must contain exactly four coordinates")
    try:
        values = [float(value) for value in box]
    except (TypeError, ValueError) as exc:
        raise ValueError("Visual grounding coordinates must be numeric") from exc
    if not all(math.isfinite(value) for value in values):
        raise ValueError("Visual grounding coordinates must be finite")

    if coordinate_space == "percent":
        x_scale = y_scale = 100.0
    elif coordinate_space == "grid_1000":
        x_scale = y_scale = 1000.0
    elif coordinate_space == "pixels":
        if not image_width or not image_height or image_width <= 0 or image_height <= 0:
            raise ValueError("Pixel boxes require positive image_width and image_height")
        x_scale, y_scale = float(image_width), float(image_height)
    else:
        raise ValueError(f"Unsupported coordinate space: {coordinate_space}")

    x1, y1, x2, y2 = values
    x1, x2 = sorted((max(0.0, min(x_scale, x1)), max(0.0, min(x_scale, x2))))
    y1, y2 = sorted((max(0.0, min(y_scale, y1)), max(0.0, min(y_scale, y2))))
    return [round(x1 / x_scale * 100.0, 4), round(y1 / y_scale * 100.0, 4),
            round(x2 / x_scale * 100.0, 4), round(y2 / y_scale * 100.0, 4)]


def parse_geochat_grounding(
    response_text: str,
    img_width: Optional[int] = None,
    img_height: Optional[int] = None
) -> List[Dict[str, Any]]:
    """
    Parses GeoChat output text containing region tags and coordinate tokens.

    GeoChat output format example:
        "In the image, there are <p>two bridges</p> {<69><51><73><75>|<1>}<delim>{<69><46><73><70>|<1>}
         positioned close to each other. Nearby, there are <p>some buildings</p> {<39><16><47><28>|<90>}."

    Args:
        response_text: Raw output string generated by GeoChat model.
        img_width: Optional width of source image in pixels for pixel coordinate scaling.
        img_height: Optional height of source image in pixels for pixel coordinate scaling.

    Returns:
        List of structured grounding objects matching the visual_evidence schema:
        [
            {
                "label": "two bridges",
                "box_normalized": [51, 69, 75, 73], # [xmin, ymin, xmax, ymax] in range 0-100
                "box_pixels": [408, 690, 600, 730],   # [xmin, ymin, xmax, ymax] if dimensions provided
                "score_token": "1"
            },
            ...
        ]
    """
    evidence = []

    # Pattern matches optional <p>label</p> followed by one or more coordinate tokens:
    # {<ymin><xmin><ymax><xmax>|<score>}
    # Note: GeoChat outputs tokens in order: ymin, xmin, ymax, xmax.
    tag_block_pattern = r"(?:<p>(.*?)</p>\s*)?((?:\{<\d+><\d+><\d+><\d+>\|[^}]+\}\s*(?:<delim>\s*)?)+)"
    box_token_pattern = r"\{<(\d+)><(\d+)><(\d+)><(\d+)>\|([^}]+)\}"

    current_label = "object"
    
    # Process blocks of region tags + coordinate sets
    for match in re.finditer(tag_block_pattern, response_text):
        label_match, box_tokens_str = match.groups()
        if label_match:
            current_label = label_match.strip()

        for box_match in re.finditer(box_token_pattern, box_tokens_str):
            ymin_n, xmin_n, ymax_n, xmax_n, score_tok = box_match.groups()
            ymin_n, xmin_n, ymax_n, xmax_n = map(int, (ymin_n, xmin_n, ymax_n, xmax_n))

            # GeoChat native token coordinates are a 0--100 grid.
            norm_box = normalize_visual_box([xmin_n, ymin_n, xmax_n, ymax_n])

            item = {
                "label": current_label,
                "box_normalized": norm_box,
                "score_token": score_tok.strip()
            }

            if img_width is not None and img_height is not None:
                xmin_px = int(norm_box[0] / 100.0 * img_width)
                ymin_px = int(norm_box[1] / 100.0 * img_height)
                xmax_px = int(norm_box[2] / 100.0 * img_width)
                ymax_px = int(norm_box[3] / 100.0 * img_height)
                item["box_pixels"] = [xmin_px, ymin_px, xmax_px, ymax_px]

            evidence.append(item)

    # Fallback parser if tag_block_pattern missed standalone coordinate tokens
    if not evidence:
        for box_match in re.finditer(box_token_pattern, response_text):
            ymin_n, xmin_n, ymax_n, xmax_n, score_tok = box_match.groups()
            ymin_n, xmin_n, ymax_n, xmax_n = map(int, (ymin_n, xmin_n, ymax_n, xmax_n))
            norm_box = normalize_visual_box([xmin_n, ymin_n, xmax_n, ymax_n])
            item = {
                "label": "detected_object",
                "box_normalized": norm_box,
                "score_token": score_tok.strip()
            }
            if img_width is not None and img_height is not None:
                item["box_pixels"] = [
                    int(norm_box[0] / 100.0 * img_width), int(norm_box[1] / 100.0 * img_height),
                    int(norm_box[2] / 100.0 * img_width), int(norm_box[3] / 100.0 * img_height)
                ]
            evidence.append(item)

    return evidence


# ── Unit Test Suite ────────────────────────────────────────────────────────────

def test_parse_geochat_grounding():
    """Unit test fixture using actual captured GeoChat model output."""
    raw_fixture = (
        "In the image, there are <p>two bridges</p> {<69><51><73><75>|<1>}<delim>{<69><46><73><70>|<1>}  "
        "positioned close to each other at the right side. Nearby, there are <p>some buildings</p> "
        "{<39><16><47><28>|<90>}<delim>{<52><15><64><27>|<90>}  clustered together at the top."
    )

    parsed = parse_geochat_grounding(raw_fixture, img_width=800, img_height=1000)

    assert len(parsed) == 4, f"Expected 4 items, got {len(parsed)}"

    # Item 1: Bridge 1
    assert parsed[0]["label"] == "two bridges"
    assert parsed[0]["box_normalized"] == [51, 69, 75, 73]
    assert parsed[0]["box_pixels"] == [408, 690, 600, 730]
    assert parsed[0]["score_token"] == "<1>"

    # Item 2: Bridge 2
    assert parsed[1]["label"] == "two bridges"
    assert parsed[1]["box_normalized"] == [46, 69, 70, 73]
    assert parsed[1]["box_pixels"] == [368, 690, 560, 730]
    assert parsed[1]["score_token"] == "<1>"

    # Item 3: Buildings 1
    assert parsed[2]["label"] == "some buildings"
    assert parsed[2]["box_normalized"] == [16, 39, 28, 47]
    assert parsed[2]["box_pixels"] == [128, 390, 224, 470]
    assert parsed[2]["score_token"] == "<90>"

    # Item 4: Buildings 2
    assert parsed[3]["label"] == "some buildings"
    assert parsed[3]["box_normalized"] == [15, 52, 27, 64]
    assert parsed[3]["box_pixels"] == [120, 520, 216, 640]
    assert parsed[3]["score_token"] == "<90>"

    print("All grounding_parser unit tests passed successfully!")


if __name__ == "__main__":
    test_parse_geochat_grounding()
